name: cowsay dragon wf

on:
  workflow_dispatch:

jobs:
  cowsay_dragon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Make script executable and run it
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
